import fs from "fs";
import path from "path";
import type {
  DocsSyncBinding,
  DocsSyncBindArgs,
  DocsSyncConfig,
  DocsSyncDeploymentBinding,
  DocsSyncDeploymentEntry,
  DocsSyncDeploymentsConfig,
  DocsSyncFileInfo,
  DocsSyncLinkEntry,
  DocsSyncLinksBinding,
  DocsSyncLinksConfig,
  DocsSyncMapping,
  DocsSyncOptions,
  DocsSyncPreviewAction,
  DocsSyncPreviewItem,
  DocsSyncProjectInfo,
  DocsSyncProjectsConfig,
  YapiRequest,
} from "../types";
import type { DiagramRenderMetric } from "../../docs/markdown";
import {
  buildDocsSyncHash,
  buildEnvUrl,
  buildInterfaceWebUrl,
  findGitRoot,
  formatBytes,
  globalConfigPath,
  initConfigIfMissing,
  looksLikeAuthError,
  normalizeProjectEnvs,
  parseJsonMaybe,
  parsePayloadLimit,
  parseSimpleToml,
  resolveToken,
} from "../utils";
import { HttpStatusError, buildUrl, fetchWithTimeout } from "../http";
import {
  isD2Available,
  isGraphvizAvailable,
  isMmdcAvailable,
  isPandocAvailable,
  isPlantUmlAvailable,
  probeMermaidRuntime,
} from "../../docs/markdown";
import {
  buildPayloadMarkdownField,
  listSourceDocFiles,
  loadSourceDoc,
  renderSourceDocToHtml,
  resolveConflicts,
} from "../../docs/source-doc";
import { YApiAuthService } from "../../services/yapi/auth";

// --- docs-sync home / config helpers ---

function findDocsSyncHome(startDir: string): string | null {
  let current = path.resolve(startDir);
  while (true) {
    const candidate = path.join(current, ".yapi");
    if (fs.existsSync(candidate) && fs.statSync(candidate).isDirectory()) {
      return candidate;
    }
    const parent = path.dirname(current);
    if (parent === current) return null;
    current = parent;
  }
}

function resolveDocsSyncHome(startDir: string, ensure: boolean): string | null {
  const found = findDocsSyncHome(startDir);
  if (found) return found;
  if (!ensure) return null;
  const home = path.join(path.resolve(startDir), ".yapi");
  fs.mkdirSync(home, { recursive: true });
  ensureDocsSyncReadme(home);
  return home;
}

function globalYapiHomeDir(): string {
  return path.resolve(process.env.YAPI_HOME || path.join(require("os").homedir(), ".yapi"));
}

function normalizeComparablePath(targetPath: string): string {
  try {
    return fs.realpathSync.native(targetPath);
  } catch {
    return path.resolve(targetPath);
  }
}

function isGlobalDocsSyncHome(homeDir: string): boolean {
  return normalizeComparablePath(homeDir) === normalizeComparablePath(globalYapiHomeDir());
}

function docsSyncConfigPath(homeDir: string): string {
  return path.join(homeDir, "docs-sync.json");
}

function docsSyncLinksPath(homeDir: string): string {
  return path.join(homeDir, "docs-sync.links.json");
}

function docsSyncProjectsPath(homeDir: string): string {
  return path.join(homeDir, "docs-sync.projects.json");
}

function docsSyncDeploymentsPath(homeDir: string): string {
  return path.join(homeDir, "docs-sync.deployments.json");
}

const DOCS_SYNC_README = [
  "# YApi Docs Sync",
  "",
  "This folder is generated by the yapi docs-sync tool.",
  "Extra caches are written when running docs-sync with bindings.",
  "",
  "Project: https://github.com/leeguooooo/cross-request-master",
  "",
  "Files:",
  "- docs-sync.json: bindings and file-to-doc ID mapping.",
  "- docs-sync.links.json: local docs to YApi doc URLs.",
  "- docs-sync.projects.json: cached project metadata/envs.",
  "- docs-sync.deployments.json: local docs to deployed URLs.",
].join("\n");

function ensureDocsSyncReadme(homeDir: string): void {
  const readmePath = path.join(homeDir, "README.md");
  if (fs.existsSync(readmePath)) return;
  fs.writeFileSync(readmePath, `${DOCS_SYNC_README}\n`, "utf8");
}

function loadDocsSyncConfig(homeDir: string): DocsSyncConfig {
  const configPath = docsSyncConfigPath(homeDir);
  if (!fs.existsSync(configPath)) {
    return { version: 1, bindings: {} };
  }
  const raw = fs.readFileSync(configPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<DocsSyncConfig>;
  const bindings = parsed.bindings && typeof parsed.bindings === "object" ? parsed.bindings : {};
  return {
    version: typeof parsed.version === "number" ? parsed.version : 1,
    bindings: bindings as Record<string, DocsSyncBinding>,
  };
}

function saveDocsSyncConfig(homeDir: string, config: DocsSyncConfig): void {
  const configPath = docsSyncConfigPath(homeDir);
  fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

function loadDocsSyncLinks(homeDir: string): DocsSyncLinksConfig {
  const configPath = docsSyncLinksPath(homeDir);
  if (!fs.existsSync(configPath)) {
    return { version: 1, bindings: {} };
  }
  const raw = fs.readFileSync(configPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<DocsSyncLinksConfig>;
  const bindings = parsed.bindings && typeof parsed.bindings === "object" ? parsed.bindings : {};
  return {
    version: typeof parsed.version === "number" ? parsed.version : 1,
    bindings: bindings as Record<string, DocsSyncLinksBinding>,
  };
}

function saveDocsSyncLinks(homeDir: string, config: DocsSyncLinksConfig): void {
  const configPath = docsSyncLinksPath(homeDir);
  fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

function loadDocsSyncProjects(homeDir: string): DocsSyncProjectsConfig {
  const configPath = docsSyncProjectsPath(homeDir);
  if (!fs.existsSync(configPath)) {
    return { version: 1, projects: {} };
  }
  const raw = fs.readFileSync(configPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<DocsSyncProjectsConfig>;
  const projects = parsed.projects && typeof parsed.projects === "object" ? parsed.projects : {};
  return {
    version: typeof parsed.version === "number" ? parsed.version : 1,
    projects: projects as Record<string, DocsSyncProjectInfo>,
  };
}

function saveDocsSyncProjects(homeDir: string, config: DocsSyncProjectsConfig): void {
  const configPath = docsSyncProjectsPath(homeDir);
  fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

function loadDocsSyncDeployments(homeDir: string): DocsSyncDeploymentsConfig {
  const configPath = docsSyncDeploymentsPath(homeDir);
  if (!fs.existsSync(configPath)) {
    return { version: 1, bindings: {} };
  }
  const raw = fs.readFileSync(configPath, "utf8");
  const parsed = JSON.parse(raw) as Partial<DocsSyncDeploymentsConfig>;
  const bindings = parsed.bindings && typeof parsed.bindings === "object" ? parsed.bindings : {};
  return {
    version: typeof parsed.version === "number" ? parsed.version : 1,
    bindings: bindings as Record<string, DocsSyncDeploymentBinding>,
  };
}

function saveDocsSyncDeployments(homeDir: string, config: DocsSyncDeploymentsConfig): void {
  const configPath = docsSyncDeploymentsPath(homeDir);
  fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");
}

// --- binding dir helpers ---

const SCAN_EXCLUDE_DIRS = new Set([
  "node_modules",
  ".git",
  ".yapi",
  "dist",
  "build",
  ".next",
  ".astro",
  "coverage",
  "out",
  ".turbo",
  ".cache",
]);

function findBindingDirCandidates(
  scanRoot: string,
  expectedFiles: string[],
  maxDepth = 4,
): { relativeDir: string; matchCount: number; total: number }[] {
  if (!expectedFiles.length) return [];
  const total = expectedFiles.length;
  const expectedSet = new Set(expectedFiles);
  const matches: { relativeDir: string; matchCount: number; total: number }[] = [];

  const walk = (currentDir: string, depth: number): void => {
    if (depth > maxDepth) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(currentDir, { withFileTypes: true });
    } catch {
      return;
    }
    let matchCount = 0;
    for (const entry of entries) {
      if (entry.isFile() && expectedSet.has(entry.name)) {
        matchCount++;
      }
    }
    if (matchCount > 0) {
      const rel = path.relative(scanRoot, currentDir);
      if (rel) {
        matches.push({ relativeDir: rel, matchCount, total });
      }
    }
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (SCAN_EXCLUDE_DIRS.has(entry.name)) continue;
      if (entry.name.startsWith(".")) continue;
      walk(path.join(currentDir, entry.name), depth + 1);
    }
  };

  walk(scanRoot, 0);
  return matches
    .filter((item) => item.matchCount * 2 >= item.total)
    .sort((a, b) => b.matchCount - a.matchCount || a.relativeDir.localeCompare(b.relativeDir));
}

function buildMissingBindingDirMessage(
  bindingName: string,
  bindingDir: string,
  binding: DocsSyncBinding,
  scanRoot: string,
): string {
  const expectedFiles = binding.files ? Object.keys(binding.files).sort() : [];
  const candidates = findBindingDirCandidates(scanRoot, expectedFiles);
  const lines: string[] = [];
  lines.push(`binding '${bindingName}' dir=${bindingDir} 在当前仓库找不到。`);
  if (candidates.length > 0) {
    const top = candidates[0];
    lines.push(`候选目录（命中 ${top.matchCount}/${top.total} 文件）：`);
    lines.push(`  ${top.relativeDir}`);
    if (candidates.length > 1) {
      const others = candidates
        .slice(1, 4)
        .map((c) => `  ${c.relativeDir} (命中 ${c.matchCount}/${c.total})`);
      lines.push("其它候选：");
      lines.push(...others);
    }
    lines.push(
      `hint: yapi docs-sync bind update --name ${bindingName} --dir ${top.relativeDir}`,
    );
  } else {
    lines.push(
      `hint: yapi docs-sync bind update --name ${bindingName} --dir <new-relative-path>`,
    );
  }
  return lines.join("\n");
}

function getBindingBaseDir(homeDir: string, rootDir: string, cwd: string): {
  baseDir: string;
  gitRoot: string | null;
  usedGitRoot: boolean;
} {
  if (!isGlobalDocsSyncHome(homeDir)) {
    return { baseDir: rootDir, gitRoot: findGitRoot(cwd), usedGitRoot: false };
  }
  const gitRoot = findGitRoot(cwd);
  if (gitRoot) {
    return { baseDir: gitRoot, gitRoot, usedGitRoot: true };
  }
  return { baseDir: path.resolve(cwd), gitRoot: null, usedGitRoot: false };
}

function normalizeBindingDirForContext(
  homeDir: string,
  rootDir: string,
  cwd: string,
  bindingDir: string,
): string {
  const context = getBindingBaseDir(homeDir, rootDir, cwd);
  const resolved = path.isAbsolute(bindingDir)
    ? bindingDir
    : path.resolve(context.baseDir, bindingDir);
  const relative = path.relative(rootDir, resolved);
  if (!relative || relative === ".") return ".";
  if (relative.startsWith("..") || path.isAbsolute(relative)) return resolved;
  return relative;
}

function resolveBindingDirForContext(
  homeDir: string,
  rootDir: string,
  cwd: string,
  bindingDir: string,
): string {
  if (!bindingDir) return rootDir;
  if (path.isAbsolute(bindingDir)) return bindingDir;
  const direct = path.resolve(rootDir, bindingDir);
  if (!isGlobalDocsSyncHome(homeDir)) return direct;
  if (fs.existsSync(direct)) return direct;
  const { baseDir } = getBindingBaseDir(homeDir, rootDir, cwd);
  const contextual = path.resolve(baseDir, bindingDir);
  if (fs.existsSync(contextual)) return contextual;
  return direct;
}

function suggestDocsSyncDir(startDir: string): string | null {
  const candidates = ["docs", "doc", "documentation", "release-notes"];
  for (const candidate of candidates) {
    const candidatePath = path.resolve(startDir, candidate);
    if (fs.existsSync(candidatePath) && fs.statSync(candidatePath).isDirectory()) {
      const relative = path.relative(startDir, candidatePath);
      return relative && relative !== "." ? relative : candidate;
    }
  }
  return null;
}

function loadMapping(dirPath: string): { mapping: DocsSyncMapping; mappingPath: string } {
  const mappingPath = path.join(dirPath, ".yapi.json");
  if (!fs.existsSync(mappingPath)) {
    return { mapping: {}, mappingPath };
  }
  const raw = fs.readFileSync(mappingPath, "utf8");
  const mapping = JSON.parse(raw) as DocsSyncMapping;
  return { mapping, mappingPath };
}

function saveMapping(mapping: DocsSyncMapping, mappingPath: string): void {
  fs.writeFileSync(mappingPath, `${JSON.stringify(mapping, null, 2)}\n`, "utf8");
}

function resolveSourceFiles(dirPath: string, mapping: DocsSyncMapping): string[] {
  const sources = Array.isArray(mapping.source_files) ? mapping.source_files : [];
  if (!sources.length) {
    const entries = listSourceDocFiles(dirPath);
    const { kept, dropped } = resolveConflicts(entries);
    for (const droppedFile of dropped) {
      console.warn(
        `⚠️ 检测到 ${droppedFile} 与同名 .html 共存，将上传 .html 版本；建议删除 ${droppedFile}。`,
      );
    }
    return kept
      .map((entry) => path.join(dirPath, entry.file))
      .sort((a, b) => a.localeCompare(b));
  }
  return sources.map((source) => {
    const resolved = path.isAbsolute(source) ? source : path.resolve(dirPath, source);
    if (!fs.existsSync(resolved) || !fs.statSync(resolved).isFile()) {
      throw new Error(`source file not found: ${resolved}`);
    }
    return resolved;
  });
}

function cloneMappingForSync(mapping: DocsSyncMapping, sourceFiles?: string[]): DocsSyncMapping {
  const next: DocsSyncMapping = {
    ...mapping,
    files: mapping.files ? { ...mapping.files } : {},
    file_hashes: mapping.file_hashes ? { ...mapping.file_hashes } : {},
    file_render_modes: mapping.file_render_modes ? { ...mapping.file_render_modes } : {},
  };
  if (sourceFiles?.length) {
    next.source_files = [...sourceFiles];
  }
  return next;
}

function mergeSyncState(target: DocsSyncMapping, source: DocsSyncMapping): void {
  target.project_id = source.project_id;
  target.catid = source.catid;
  target.template_id = source.template_id;
  target.files = source.files ? { ...source.files } : {};
  target.file_hashes = source.file_hashes ? { ...source.file_hashes } : {};
  target.file_render_modes = source.file_render_modes ? { ...source.file_render_modes } : {};
}

type DocsSyncRenderMode = "default" | "classic" | "no-mermaid";

type DocsSyncRetryAttempt = {
  mode: DocsSyncRenderMode;
  payloadBytes?: number;
  htmlBytes?: number;
  message?: string;
};

// --- interface helpers ---

async function listExistingInterfaces(
  catId: number,
  request: YapiRequest,
): Promise<{
  byPath: Record<string, number>;
  byTitle: Record<string, number>;
  byId: Record<string, { path?: string; title?: string }>;
}> {
  const resp = await request("/api/interface/list_cat", "GET", {
    catid: catId,
    page: 1,
    limit: 10000,
  });
  if (resp?.errcode !== 0) {
    throw new Error(`list_cat failed: ${resp?.errmsg || "unknown error"}`);
  }
  const items = resp?.data?.list || [];
  const byPath: Record<string, number> = {};
  const byTitle: Record<string, number> = {};
  const byId: Record<string, { path?: string; title?: string }> = {};
  for (const item of items) {
    const apiPath = item?.path;
    const title = item?.title;
    const itemId = item?._id;
    if (apiPath && itemId) byPath[apiPath] = Number(itemId);
    if (title && itemId) byTitle[title] = Number(itemId);
    if (itemId) {
      byId[String(itemId)] = { path: apiPath || "", title: title || "" };
    }
  }
  return { byPath, byTitle, byId };
}

function buildAddPayload(
  template: Record<string, any>,
  title: string,
  apiPath: string,
  catId: number,
  projectId: number,
): Record<string, any> {
  return {
    title,
    path: apiPath,
    method: template.method || "GET",
    catid: catId,
    project_id: projectId,
    status: template.status || "undone",
    type: template.type || "static",
    api_opened: template.api_opened || false,
    req_query: template.req_query || [],
    req_headers: template.req_headers || [],
    req_params: template.req_params || [],
    req_body_type: template.req_body_type || "json",
    req_body_form: template.req_body_form || [],
    req_body_is_json_schema: template.req_body_is_json_schema ?? true,
    res_body_type: template.res_body_type || "json",
    res_body: template.res_body || '{"type":"object","title":"title","properties":{}}',
    res_body_is_json_schema: template.res_body_is_json_schema ?? true,
    tag: template.tag || [],
  };
}

function buildUpdatePayload(
  docId: number,
  title: string | undefined,
  markdownField: string,
  html: string,
): Record<string, unknown> {
  const payload: Record<string, unknown> = { id: docId, markdown: markdownField, desc: html };
  if (title) {
    payload.title = title;
  }
  return payload;
}

function pickLargestMermaid(metrics: DiagramRenderMetric[]): DiagramRenderMetric | undefined {
  return metrics
    .filter((item) => item.renderer === "mermaid")
    .sort((a, b) => b.renderedBytes - a.renderedBytes)[0];
}

function buildDocsSyncPreviewLine(item: DocsSyncPreviewItem): string {
  const parts = [
    `file=${item.fileName}`,
    `action=${item.action}`,
    `markdown=${formatBytes(item.markdownBytes)}`,
    `html=${formatBytes(item.htmlBytes)}`,
    `payload=${formatBytes(item.payloadBytes)}`,
    `path=${item.apiPath}`,
  ];
  if (item.docId) {
    parts.push(`doc_id=${item.docId}`);
  }
  if (item.largestMermaid) {
    parts.push(
      `largest_mermaid=#${item.largestMermaid.index}`,
      `largest_mermaid_svg=${formatBytes(item.largestMermaid.renderedBytes)}`,
    );
  }
  return `preview ${parts.join(" ")}`;
}

function buildDocsSyncPayloadTooLargeMessage(
  fileName: string,
  preview: DocsSyncPreviewItem,
  error: HttpStatusError,
  attempts: DocsSyncRetryAttempt[] = [],
): string {
  const lines = [
    `413 Payload Too Large while syncing ${fileName}`,
    `- request payload: ${formatBytes(preview.payloadBytes)}`,
    `- markdown size: ${formatBytes(preview.markdownBytes)}`,
    `- rendered html size: ${formatBytes(preview.htmlBytes)}`,
  ];
  const limitBytes = parsePayloadLimit(error.body || error.message);
  if (limitBytes) {
    lines.push(`- server limit: ${formatBytes(limitBytes)}`);
  } else {
    lines.push("- server limit: unknown (response did not expose an exact value)");
  }
  if (preview.largestMermaid) {
    lines.push(
      `- largest Mermaid block: #${preview.largestMermaid.index} -> ${formatBytes(preview.largestMermaid.renderedBytes)}`,
    );
  } else {
    lines.push("- largest Mermaid block: none");
  }
  attempts.forEach((attempt) => {
    if (attempt.mode === "default") return;
    const label =
      attempt.mode === "classic" ? "--mermaid-classic" : "--no-mermaid";
    if (attempt.payloadBytes && attempt.htmlBytes) {
      lines.push(
        `- retry with ${label}: payload=${formatBytes(attempt.payloadBytes)} html=${formatBytes(attempt.htmlBytes)}`,
      );
    }
    if (attempt.message) {
      lines.push(`- ${label} retry result: ${attempt.message}`);
    }
  });
  lines.push("- suggestion: run `yapi docs-sync --dry-run ...` to preview all files before upload");
  lines.push("- suggestion: split oversized Mermaid diagrams or move them into separate docs");
  lines.push("- suggestion: if even `--no-mermaid` still hits 413, the remaining limit is on the YApi server/proxy side");
  return lines.join("\n");
}

function resolveRenderModeLabel(mode: DocsSyncRenderMode): string {
  if (mode === "classic") return "--mermaid-classic";
  if (mode === "no-mermaid") return "--no-mermaid";
  return "default Mermaid rendering";
}

function resolveDocsSyncOptionsForMode(
  options: DocsSyncOptions,
  mode: DocsSyncRenderMode,
): DocsSyncOptions {
  if (mode === "classic") {
    return {
      ...options,
      noMermaid: false,
      mermaidLook: "classic",
    };
  }
  if (mode === "no-mermaid") {
    return {
      ...options,
      noMermaid: true,
    };
  }
  return { ...options };
}

function resolveInitialRenderMode(
  options: DocsSyncOptions,
  rememberedMode?: "classic" | "no-mermaid",
): DocsSyncRenderMode {
  if (options.noMermaid) return "no-mermaid";
  if (options.mermaidLook === "classic") return "classic";
  if (rememberedMode) return rememberedMode;
  return "default";
}

function resolveRetryModes(
  mode: DocsSyncRenderMode,
  hasMermaidBlocks: boolean,
): DocsSyncRenderMode[] {
  if (!hasMermaidBlocks) return [];
  if (mode === "default") return ["classic", "no-mermaid"];
  if (mode === "classic") return ["no-mermaid"];
  return [];
}


async function addInterface(
  title: string,
  apiPath: string,
  mapping: DocsSyncMapping,
  request: YapiRequest,
): Promise<number> {
  const projectId = Number(mapping.project_id || 0);
  const catId = Number(mapping.catid || 0);
  if (!projectId || !catId) {
    throw new Error("project_id and catid are required to create new docs");
  }
  let template: Record<string, any> = {};
  if (mapping.template_id) {
    const resp = await request("/api/interface/get", "GET", { id: mapping.template_id });
    if (resp?.errcode !== 0) {
      throw new Error(`interface get failed: ${resp?.errmsg || "unknown error"}`);
    }
    template = resp?.data || {};
  }
  const payload = buildAddPayload(template, title, apiPath, catId, projectId);
  const resp = await request("/api/interface/add", "POST", {}, payload);
  if (resp?.errcode !== 0) {
    throw new Error(`interface add failed: ${resp?.errmsg || "unknown error"}`);
  }
  const newId = resp?.data?._id;
  if (!newId) {
    throw new Error("interface add succeeded but missing id");
  }
  return Number(newId);
}

async function updateInterface(
  docId: number,
  title: string | undefined,
  markdownField: string,
  html: string,
  request: YapiRequest,
): Promise<void> {
  const payload = buildUpdatePayload(docId, title, markdownField, html);
  const resp = await request("/api/interface/up", "POST", {}, payload);
  if (resp?.errcode !== 0) {
    throw new Error(`interface up failed: ${resp?.errmsg || "unknown error"}`);
  }
}

async function syncDocsDir(
  dirPath: string,
  mapping: DocsSyncMapping,
  options: DocsSyncOptions,
  request: YapiRequest,
): Promise<{
  updated: number;
  created: number;
  skipped: number;
  previewOnly: number;
  files: Record<string, DocsSyncFileInfo>;
  previews: DocsSyncPreviewItem[];
}> {
  if (!mapping.files || typeof mapping.files !== "object") {
    mapping.files = {};
  }
  if (!mapping.file_hashes || typeof mapping.file_hashes !== "object") {
    mapping.file_hashes = {};
  }

  const envProjectId = process.env.YAPI_PROJECT_ID;
  const envCatId = process.env.YAPI_CATID;
  const envTemplateId = process.env.YAPI_TEMPLATE_ID;
  if (!mapping.project_id && envProjectId) mapping.project_id = Number(envProjectId);
  if (!mapping.catid && envCatId) mapping.catid = Number(envCatId);
  if (!mapping.template_id && envTemplateId) mapping.template_id = Number(envTemplateId);

  const hasTarget = Boolean(mapping.project_id && mapping.catid);
  if (!hasTarget && !options.dryRun) {
    throw new Error(
      "缺少 project_id/catid。请先绑定或配置：yapi docs-sync bind add --name <binding> --dir <path> --project-id <id> --catid <id>，或在目录下添加 .yapi.json，或设置环境变量 YAPI_PROJECT_ID/YAPI_CATID。"
    );
  }

  const { byPath, byTitle, byId } = hasTarget
    ? await listExistingInterfaces(Number(mapping.catid), request)
    : { byPath: {}, byTitle: {}, byId: {} };

  let updated = 0;
  let created = 0;
  let skipped = 0;
  let previewOnly = 0;
  const fileInfos: Record<string, DocsSyncFileInfo> = {};
  const previews: DocsSyncPreviewItem[] = [];
  const files = resolveSourceFiles(dirPath, mapping);
  for (const mdPath of files) {
    const stem = path.parse(mdPath).name;
    const relName = path.basename(mdPath);
    const apiPath = `/${stem}`;

    const doc = loadSourceDoc(mdPath, relName);
    const desiredTitle = doc.title || stem;

    let docId = mapping.files[relName];
    if (!docId) {
      docId = byPath[apiPath] || byTitle[desiredTitle] || byTitle[stem];
      if (docId) mapping.files[relName] = docId;
    }

    let action: DocsSyncPreviewAction = docId ? "update" : hasTarget ? "create" : "preview-only";

    if (!docId && hasTarget) {
      created += 1;
      if (!options.dryRun) {
        docId = await addInterface(desiredTitle, apiPath, mapping, request);
        mapping.files[relName] = docId;
      }
    }
    if (!docId && !hasTarget) {
      previewOnly += 1;
    }

    if (docId) {
      const resolvedPath = byId[String(docId)]?.path || apiPath;
      fileInfos[relName] = { docId: Number(docId), apiPath: resolvedPath };
    }

    const logPrefix = `[docs-sync:${relName}]`;
    const hasMermaidBlocks =
      doc.kind === "markdown" && /```mermaid\s*\r?\n/i.test(doc.raw);
    const rememberedMode =
      !options.noMermaid && options.mermaidLook === "handDrawn"
        ? mapping.file_render_modes?.[relName]
        : undefined;
    let appliedMode = resolveInitialRenderMode(options, rememberedMode);
    let effectiveOptions = resolveDocsSyncOptionsForMode(options, appliedMode);
    if (rememberedMode) {
      console.log(`${logPrefix} using remembered fallback: ${resolveRenderModeLabel(appliedMode)}.`);
    }

    let contentHash = buildDocsSyncHash(doc, effectiveOptions);
    const previousHash = mapping.file_hashes[relName];
    const currentTitle = docId ? byId[String(docId)]?.title : "";
    const titleToUpdate = !docId
      ? undefined
      : !currentTitle || currentTitle !== desiredTitle
        ? desiredTitle
        : undefined;
    const shouldSyncTitle = Boolean(titleToUpdate);
    const shouldSkipUnchanged =
      !options.force &&
      docId &&
      previousHash &&
      previousHash === contentHash &&
      !shouldSyncTitle;

    if (shouldSkipUnchanged && !options.dryRun) {
      skipped += 1;
      continue;
    }

    let { html, mermaidFailed, diagramFailed, diagramMetrics } = renderSourceDocToHtml(
      doc,
      effectiveOptions,
      logPrefix,
    );

    if (shouldSkipUnchanged) {
      action = "skip";
      skipped += 1;
    }

    const payloadObject =
      docId && action !== "create"
        ? buildUpdatePayload(docId, titleToUpdate, buildPayloadMarkdownField(doc), html)
        : buildAddPayload({}, desiredTitle, apiPath, Number(mapping.catid || 0), Number(mapping.project_id || 0));
    const preview: DocsSyncPreviewItem = {
      fileName: relName,
      action,
      markdownBytes: Buffer.byteLength(doc.raw, "utf8"),
      htmlBytes: Buffer.byteLength(html, "utf8"),
      payloadBytes: Buffer.byteLength(JSON.stringify(payloadObject), "utf8"),
      apiPath: docId ? fileInfos[relName]?.apiPath || apiPath : apiPath,
      docId: docId ? Number(docId) : undefined,
      largestMermaid: pickLargestMermaid(diagramMetrics),
    };
    previews.push(preview);

    if (!options.dryRun && docId && action !== "skip") {
      try {
        await updateInterface(docId, titleToUpdate, buildPayloadMarkdownField(doc), html, request);
      } catch (error) {
        if (error instanceof HttpStatusError && error.status === 413) {
          const attempts: DocsSyncRetryAttempt[] = [];
          let resolved = false;
          for (const retryMode of resolveRetryModes(appliedMode, hasMermaidBlocks)) {
            console.warn(
              `${logPrefix} 413 received, retrying with ${resolveRenderModeLabel(retryMode)} for this file.`,
            );
            const retryAttempt: DocsSyncRetryAttempt = { mode: retryMode };
            attempts.push(retryAttempt);
            try {
              const retryOptions = resolveDocsSyncOptionsForMode(options, retryMode);
              const retryResult = renderSourceDocToHtml(doc, retryOptions, logPrefix);
              const retryPayload = buildUpdatePayload(
                docId,
                titleToUpdate,
                buildPayloadMarkdownField(doc),
                retryResult.html,
              );
              retryAttempt.payloadBytes = Buffer.byteLength(JSON.stringify(retryPayload), "utf8");
              retryAttempt.htmlBytes = Buffer.byteLength(retryResult.html, "utf8");
              await updateInterface(docId, titleToUpdate, buildPayloadMarkdownField(doc), retryResult.html, request);
              html = retryResult.html;
              mermaidFailed = retryResult.mermaidFailed;
              diagramFailed = retryResult.diagramFailed;
              diagramMetrics = retryResult.diagramMetrics;
              appliedMode = retryMode;
              effectiveOptions = retryOptions;
              contentHash = buildDocsSyncHash(doc, effectiveOptions);
              resolved = true;
              break;
            } catch (retryError) {
              retryAttempt.message =
                retryError instanceof Error ? retryError.message : String(retryError);
            }
          }
          if (!resolved) {
            throw new Error(buildDocsSyncPayloadTooLargeMessage(relName, preview, error, attempts));
          }
        } else {
          throw error;
        }
      }
    }
    if (appliedMode === "default") {
      if (mapping.file_render_modes) {
        delete mapping.file_render_modes[relName];
      }
    } else {
      if (!mapping.file_render_modes || typeof mapping.file_render_modes !== "object") {
        mapping.file_render_modes = {};
      }
      mapping.file_render_modes[relName] = appliedMode;
    }
    if (docId && !mermaidFailed && !diagramFailed) {
      mapping.file_hashes[relName] = contentHash;
    }
    if (action !== "skip") {
      updated += 1;
    }
  }

  return { updated, created, skipped, previewOnly, files: fileInfos, previews };
}

// --- project info / env helpers ---

async function fetchProjectInfo(
  projectId: number,
  baseUrl: string,
  request: YapiRequest,
): Promise<DocsSyncProjectInfo | null> {
  if (!projectId) return null;
  const resp = await request("/api/project/get", "GET", { id: projectId });
  if (resp?.errcode !== 0) {
    throw new Error(`project get failed: ${resp?.errmsg || "unknown error"}`);
  }
  const data = resp?.data || {};
  const name = typeof data.name === "string" ? data.name : "";
  const basepath = typeof data.basepath === "string" ? data.basepath : "";
  const envs = normalizeProjectEnvs(data.env || data.envs);
  return {
    project_id: Number(projectId),
    name,
    basepath,
    envs,
    base_url: baseUrl,
  };
}

function buildEnvUrls(
  projectInfo: DocsSyncProjectInfo | null,
  apiPath: string,
): Record<string, string> {
  const urls: Record<string, string> = {};
  if (!projectInfo || !projectInfo.envs || !projectInfo.envs.length) return urls;
  const basepath = projectInfo.basepath || "";
  projectInfo.envs.forEach((env, index) => {
    const rawKey = env.name || env.domain || `env${index + 1}`;
    const url = buildEnvUrl(env.domain, basepath, apiPath);
    if (!url) return;
    let key = rawKey;
    let suffix = 1;
    while (urls[key]) {
      suffix += 1;
      key = `${rawKey}-${suffix}`;
    }
    urls[key] = url;
  });
  return urls;
}

async function updateDocsSyncCaches(
  homeDir: string,
  baseUrl: string,
  bindingResults: Record<
    string,
    { binding: DocsSyncBinding; files: Record<string, DocsSyncFileInfo> }
  >,
  request: YapiRequest,
): Promise<void> {
  const linksConfig = loadDocsSyncLinks(homeDir);
  const projectsConfig = loadDocsSyncProjects(homeDir);
  const deploymentsConfig = loadDocsSyncDeployments(homeDir);
  const projectCache = new Map<number, DocsSyncProjectInfo | null>();

  const resolveProjectInfo = async (projectId: number): Promise<DocsSyncProjectInfo | null> => {
    if (!projectId) return null;
    if (projectCache.has(projectId)) return projectCache.get(projectId) || null;
    const existing = projectsConfig.projects[String(projectId)] || null;
    try {
      const fresh = await fetchProjectInfo(projectId, baseUrl, request);
      if (fresh) {
        projectsConfig.projects[String(projectId)] = fresh;
        projectCache.set(projectId, fresh);
        return fresh;
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.warn(`project get failed (project_id=${projectId}): ${message}`);
    }
    projectCache.set(projectId, existing);
    return existing;
  };

  for (const [name, result] of Object.entries(bindingResults)) {
    const binding = result.binding;
    const projectId = Number(binding.project_id || 0);

    const linkFiles: Record<string, DocsSyncLinkEntry> = {};
    const deploymentFiles: Record<string, DocsSyncDeploymentEntry> = {};
    const projectInfo = await resolveProjectInfo(projectId);

    for (const [fileName, fileInfo] of Object.entries(result.files)) {
      const docUrl = projectId ? buildInterfaceWebUrl(baseUrl, projectId, fileInfo.docId) : "";
      linkFiles[fileName] = {
        doc_id: fileInfo.docId,
        api_path: fileInfo.apiPath,
        url: docUrl,
      };

      deploymentFiles[fileName] = {
        api_path: fileInfo.apiPath,
        env_urls: buildEnvUrls(projectInfo, fileInfo.apiPath),
      };
    }

    linksConfig.bindings[name] = {
      dir: binding.dir,
      project_id: projectId || undefined,
      catid: binding.catid,
      files: linkFiles,
    };

    deploymentsConfig.bindings[name] = {
      dir: binding.dir,
      project_id: projectId || undefined,
      files: deploymentFiles,
    };
  }

  saveDocsSyncLinks(homeDir, linksConfig);
  saveDocsSyncProjects(homeDir, projectsConfig);
  saveDocsSyncDeployments(homeDir, deploymentsConfig);
}

// --- bind subcommand ---

export async function runDocsSyncBindings(action: string, args: DocsSyncBindArgs): Promise<number> {
  if (args.help) {
    // help is handled by yargs
    return 0;
  }

  const writeActions = new Set(["add", "update", "remove", "rm", "delete", "del"]);
  const readActions = new Set(["list", "get", "show"]);
  if (!writeActions.has(action) && !readActions.has(action)) {
    console.error(`unknown docs-sync bind action: ${action}`);
    return 2;
  }

  const homeDir = resolveDocsSyncHome(process.cwd(), writeActions.has(action));
  if (!homeDir) {
    if (action === "list") {
      console.log("no docs-sync bindings (missing .yapi/docs-sync.json)");
      return 0;
    }
    console.error(
      "missing .yapi/docs-sync.json (run in project root or create one with docs-sync bind add)",
    );
    return 2;
  }

  const rootDir = path.dirname(homeDir);
  const config = loadDocsSyncConfig(homeDir);

  if (action === "list") {
    const entries = Object.entries(config.bindings).sort(([a], [b]) => a.localeCompare(b));
    if (!entries.length) {
      console.log("no docs-sync bindings");
      return 0;
    }
    for (const [name, binding] of entries) {
      const filesCount = binding.files ? Object.keys(binding.files).length : 0;
      console.log(
        `${name} dir=${binding.dir} project_id=${binding.project_id ?? ""} catid=${binding.catid ?? ""}` +
          (binding.template_id ? ` template_id=${binding.template_id}` : "") +
          ` files=${filesCount}`,
      );
    }
    return 0;
  }

  if (!args.name) {
    console.error("missing --name for docs-sync bind action");
    return 2;
  }

  if (action === "get" || action === "show") {
    const binding = config.bindings[args.name];
    if (!binding) {
      console.error(`binding not found: ${args.name}`);
      return 2;
    }
    const fileDocIds = binding.files && typeof binding.files === "object" ? binding.files : {};
    const fileHashes =
      binding.file_hashes && typeof binding.file_hashes === "object" ? binding.file_hashes : {};
    const fileLastSyncedAt =
      (binding as DocsSyncBinding & { file_last_synced_at?: Record<string, string> })
        .file_last_synced_at || {};
    const fileNames = Array.from(new Set([...Object.keys(fileDocIds), ...Object.keys(fileHashes)]))
      .sort((a, b) => a.localeCompare(b));
    const files = fileNames.reduce<Record<string, Record<string, string | number>>>(
      (result, fileName) => {
        const entry: Record<string, string | number> = {};
        if (typeof fileHashes[fileName] === "string") {
          entry.hash = fileHashes[fileName];
        }
        if (typeof fileDocIds[fileName] === "number") {
          entry.doc_id = fileDocIds[fileName];
        }
        if (typeof fileLastSyncedAt[fileName] === "string") {
          entry.last_synced_at = fileLastSyncedAt[fileName];
        }
        result[fileName] = entry;
        return result;
      },
      {},
    );
    const payload: Record<string, unknown> = {
      name: args.name,
      dir: binding.dir,
      project_id: binding.project_id,
      catid: binding.catid,
      files,
    };
    if (binding.template_id !== undefined) {
      payload.template_id = binding.template_id;
    }
    console.log(JSON.stringify(payload, null, 2));
    console.log("summary:");
    console.log(`binding ${args.name} -> dir=${binding.dir}`);
    console.log(
      `project_id=${binding.project_id ?? ""} catid=${binding.catid ?? ""}` +
        (binding.template_id !== undefined ? ` template_id=${binding.template_id}` : ""),
    );
    console.log(`files=${fileNames.length}`);
    return 0;
  }

  if (action === "remove" || action === "rm" || action === "delete" || action === "del") {
    if (!config.bindings[args.name]) {
      console.error(`binding not found: ${args.name}`);
      return 2;
    }
    delete config.bindings[args.name];
    saveDocsSyncConfig(homeDir, config);
    console.log(`binding removed: ${args.name}`);
    return 0;
  }

  const hasExisting = Boolean(config.bindings[args.name]);
  if (action === "add" && hasExisting) {
    console.error(`binding already exists: ${args.name}`);
    return 2;
  }
  if (action === "update" && !hasExisting) {
    console.error(`binding not found: ${args.name}`);
    return 2;
  }

  if (action === "add") {
    if (
      !args.dir ||
      !Number.isFinite(args.projectId ?? NaN) ||
      !Number.isFinite(args.catId ?? NaN)
    ) {
      console.error("add requires --dir, --project-id, and --catid");
      return 2;
    }
  }

  const existing = config.bindings[args.name] || ({} as DocsSyncBinding);
  const next: DocsSyncBinding = {
    dir: existing.dir || "",
    project_id: existing.project_id,
    catid: existing.catid,
    template_id: existing.template_id,
    source_files: existing.source_files ? [...existing.source_files] : undefined,
    files: existing.files ? { ...existing.files } : {},
    file_hashes: existing.file_hashes ? { ...existing.file_hashes } : {},
  };

  if (args.dir) {
    next.dir = normalizeBindingDirForContext(homeDir, rootDir, process.cwd(), args.dir);
  }
  if (args.projectId !== undefined && Number.isFinite(args.projectId)) {
    next.project_id = Number(args.projectId);
  }
  if (args.catId !== undefined && Number.isFinite(args.catId)) {
    next.catid = Number(args.catId);
  }
  if (args.templateId !== undefined && Number.isFinite(args.templateId)) {
    next.template_id = Number(args.templateId);
  }
  if (args.clearSourceFiles) {
    next.source_files = [];
  } else if (args.sourceFiles && args.sourceFiles.length) {
    next.source_files = args.sourceFiles;
  }

  if (!next.dir || !next.project_id || !next.catid) {
    console.error("binding requires dir/project_id/catid");
    return 2;
  }

  config.bindings[args.name] = next;
  saveDocsSyncConfig(homeDir, config);
  const resolvedDir = resolveBindingDirForContext(homeDir, rootDir, process.cwd(), next.dir);
  console.log(`${action === "add" ? "binding added" : "binding updated"}: ${args.name}`);
  console.log(`stored_dir=${next.dir}`);
  console.log(`resolved_dir=${resolvedDir}`);
  const gitRoot = findGitRoot(process.cwd());
  if (gitRoot) {
    console.log(`git_root=${gitRoot}`);
  } else if (isGlobalDocsSyncHome(homeDir)) {
    console.warn("warning: no git root detected, relative --dir was resolved from current working directory");
  }
  return 0;
}

// --- main docs-sync command ---

function resolveWatchTargets(options: DocsSyncOptions): string[] {
  const targets = new Set<string>();
  for (const dir of options.dirs || []) {
    const resolved = path.resolve(dir);
    if (fs.existsSync(resolved) && fs.statSync(resolved).isDirectory()) {
      targets.add(resolved);
    }
  }
  if (options.bindings && options.bindings.length > 0) {
    const home = resolveDocsSyncHome(process.cwd(), false);
    if (home) {
      const config = loadDocsSyncConfig(home);
      const rootDir = path.dirname(home);
      for (const name of options.bindings) {
        const binding = config.bindings[name];
        if (!binding) continue;
        const dirPath = resolveBindingDirForContext(home, rootDir, process.cwd(), binding.dir);
        if (fs.existsSync(dirPath) && fs.statSync(dirPath).isDirectory()) {
          targets.add(dirPath);
        }
      }
    }
  }
  return Array.from(targets);
}

export async function runDocsSyncWatch(options: DocsSyncOptions): Promise<number> {
  const debounceMs =
    typeof options.watchDebounceMs === "number" && options.watchDebounceMs > 0
      ? options.watchDebounceMs
      : 500;
  const innerOptions: DocsSyncOptions = { ...options, watch: false };

  console.log("[watch] running initial sync...");
  let initialCode = 0;
  try {
    initialCode = await runDocsSync(innerOptions);
  } catch (error) {
    console.error(
      "[watch] initial sync threw:",
      error instanceof Error ? error.message : String(error),
    );
    initialCode = 2;
  }
  if (initialCode !== 0) {
    console.warn(`[watch] initial sync exited with ${initialCode}; continuing to watch anyway`);
  }

  const targets = resolveWatchTargets(options);
  if (targets.length === 0) {
    console.error(
      "[watch] no directories to watch (use --dir <path> or --binding <name>); exiting",
    );
    return 2;
  }

  console.log(`[watch] watching ${targets.length} dir(s):`);
  for (const t of targets) console.log(`  - ${t}`);
  console.log(`[watch] debounce=${debounceMs}ms (Ctrl+C to stop)`);

  let pending: NodeJS.Timeout | null = null;
  let syncing = false;
  const triggerSync = (): void => {
    if (pending) clearTimeout(pending);
    pending = setTimeout(async () => {
      pending = null;
      if (syncing) {
        triggerSync();
        return;
      }
      syncing = true;
      const ts = new Date().toISOString();
      console.log(`[watch] [${ts}] syncing...`);
      try {
        const code = await runDocsSync(innerOptions);
        console.log(`[watch] sync ${code === 0 ? "ok" : `exited ${code}`}`);
      } catch (error) {
        console.error(
          "[watch] sync threw:",
          error instanceof Error ? error.message : String(error),
        );
      } finally {
        syncing = false;
      }
    }, debounceMs);
  };

  const watchers: fs.FSWatcher[] = [];
  for (const target of targets) {
    try {
      const watcher = fs.watch(target, { recursive: true }, (_event, filename) => {
        if (!filename) return;
        const name = String(filename);
        if (!name.endsWith(".md") && !name.endsWith(".html")) return;
        console.log(`[watch] change detected: ${name}`);
        triggerSync();
      });
      watchers.push(watcher);
    } catch (error) {
      console.error(
        `[watch] failed to watch ${target}:`,
        error instanceof Error ? error.message : String(error),
      );
    }
  }
  if (watchers.length === 0) {
    console.error("[watch] no watchers could be installed; exiting");
    return 2;
  }

  return await new Promise<number>((resolve) => {
    const cleanup = (): void => {
      console.log("\n[watch] stopping...");
      for (const w of watchers) {
        try {
          w.close();
        } catch {
          /* ignore */
        }
      }
      if (pending) clearTimeout(pending);
      resolve(0);
    };
    process.once("SIGINT", cleanup);
    process.once("SIGTERM", cleanup);
  });
}

export async function runDocsSync(options: DocsSyncOptions): Promise<number> {
  if (options.watch) {
    return await runDocsSyncWatch(options);
  }
  try {
    if (!isPandocAvailable()) {
      console.warn("pandoc not found, fallback to markdown-it renderer.");
      console.warn("Install pandoc (macOS): brew install pandoc");
      console.warn("More info: https://pandoc.org/installing.html");
    }
    if (!options.noMermaid && !isMmdcAvailable()) {
      console.warn("mmdc not found, Mermaid blocks will stay as code.");
      console.warn("Install mermaid-cli: npm i -g @mermaid-js/mermaid-cli");
    } else if (!options.noMermaid) {
      const mermaidRuntime = probeMermaidRuntime({
        look: options.mermaidLook,
        handDrawnSeed: options.mermaidHandDrawnSeed,
      });
      if (!mermaidRuntime.ok) {
        console.warn(`mermaid runtime check failed: ${mermaidRuntime.message}`);
      }
    }
    if (!isPlantUmlAvailable()) {
      console.warn("plantuml not found, PlantUML blocks will be removed from HTML.");
      console.warn("Install PlantUML (macOS): brew install plantuml");
    }
    if (!isGraphvizAvailable()) {
      console.warn("graphviz (dot) not found, Graphviz blocks will be removed from HTML.");
      console.warn("Install Graphviz (macOS): brew install graphviz");
    }
    if (!isD2Available()) {
      console.warn("d2 not found, D2 blocks will be removed from HTML.");
      console.warn("Install D2 (macOS): brew install d2");
    }

    if (options.bindings.length && options.dirs.length) {
      console.error("use --binding or --dir, not both");
      return 2;
    }

    const docsSyncHome = resolveDocsSyncHome(process.cwd(), false);
    const docsSyncConfig = docsSyncHome ? loadDocsSyncConfig(docsSyncHome) : null;
    let bindingNames = options.bindings;
    let useBindings = bindingNames.length > 0;
    if (
      !useBindings &&
      !options.dirs.length &&
      docsSyncConfig &&
      Object.keys(docsSyncConfig.bindings).length
    ) {
      useBindings = true;
      bindingNames = Object.keys(docsSyncConfig.bindings);
    }

    if (useBindings && (!docsSyncHome || !docsSyncConfig)) {
      console.error("missing .yapi/docs-sync.json (run docs-sync bind add or use --dir)");
      return 2;
    }
    if (useBindings && !bindingNames.length) {
      console.error("no docs-sync bindings found (run docs-sync bind add or use --dir)");
      return 2;
    }

    const usingDefaultDir = !useBindings && !options.dirs.length;
    const dirs = useBindings ? [] : options.dirs.length ? options.dirs : ["docs/release-notes"];
    if (!useBindings) {
      const missingDirs = dirs.filter((dir) => {
        const dirPath = path.resolve(dir);
        return !fs.existsSync(dirPath) || !fs.statSync(dirPath).isDirectory();
      });
      if (missingDirs.length) {
        const firstMissing = path.resolve(missingDirs[0]);
        console.error(`dir not found: ${firstMissing}`);
        if (usingDefaultDir) {
          const suggestion = suggestDocsSyncDir(process.cwd());
          if (suggestion) {
            console.error(`hint: pass --dir ${suggestion}`);
          }
          console.error("hint: or bind a directory with yapi docs-sync bind add");
        } else {
          console.error("hint: pass --dir <existing_dir> or bind a directory");
        }
        return 2;
      }
    }

    let config: Record<string, string> = {};
    let configPath = options.config || "";
    if (options.config) {
      if (fs.existsSync(configPath)) {
        config = parseSimpleToml(fs.readFileSync(configPath, "utf8"));
      } else {
        const init = await initConfigIfMissing(options);
        if (init) {
          config = init.config;
          configPath = init.configPath;
        } else {
          console.error(`missing config file: ${configPath}`);
          return 2;
        }
      }
    } else {
      const globalPath = globalConfigPath();
      if (fs.existsSync(globalPath)) {
        configPath = globalPath;
        config = parseSimpleToml(fs.readFileSync(globalPath, "utf8"));
      } else {
        const init = await initConfigIfMissing(options);
        if (init) {
          config = init.config;
          configPath = init.configPath;
        } else {
          console.error("missing config: create ~/.yapi/config.toml or pass --config");
          return 2;
        }
      }
    }

    const baseUrl = options.baseUrl || config.base_url || "";
    if (!baseUrl) {
      console.error("missing --base-url or config base_url");
      return 2;
    }

    const projectId = options.projectId || config.project_id || "";
    const rawToken = options.token || config.token || "";
    const token = resolveToken(rawToken, projectId);

    let authMode = (options.authMode || config.auth_mode || "").trim().toLowerCase();
    if (!authMode) {
      authMode = token
        ? "token"
        : options.email || options.password || config.email || config.password
          ? "global"
          : "token";
    }
    if (authMode !== "token" && authMode !== "global") {
      console.error("invalid --auth-mode (use token or global)");
      return 2;
    }

    const headers: Record<string, string> = {};
    const email = options.email || config.email || "";
    const password = options.password || config.password || "";
    const authService =
      authMode === "global"
        ? new YApiAuthService(baseUrl, email || "", password || "", "warn", {
            timeoutMs: options.timeout || 30000,
          })
        : null;
    const canRelogin =
      authMode === "global" &&
      Boolean(authService) &&
      Boolean(email) &&
      Boolean(password) &&
      !options.cookie;

    if (options.cookie) {
      headers.Cookie = options.cookie;
    } else if (authMode === "global") {
      const cachedCookie = authService?.getCachedCookieHeader();
      if (cachedCookie) {
        headers.Cookie = cachedCookie;
      } else if (email && password && authService) {
        try {
          headers.Cookie = await authService.getCookieHeaderWithLogin();
        } catch (error) {
          console.error(error instanceof Error ? error.message : String(error));
          return 2;
        }
      } else {
        console.error("missing email/password for global auth");
        return 2;
      }
    }

    const request: YapiRequest = async (endpoint, method, query = {}, data) => {
      const queryItems: [string, string][] = [];
      for (const [key, value] of Object.entries(query)) {
        if (value !== undefined && value !== null) {
          queryItems.push([key, String(value)]);
        }
      }
      const url = buildUrl(
        baseUrl,
        endpoint,
        queryItems,
        authMode === "token" ? token : "",
        options.tokenParam || "token",
      );

      let body: string | undefined;
      if (data !== undefined) {
        body = JSON.stringify(data);
      }

      const sendOnce = async () => {
        const requestHeaders: Record<string, string> = { ...headers };
        if (body !== undefined) {
          requestHeaders["Content-Type"] = "application/json;charset=UTF-8";
        }
        const response = await fetchWithTimeout(
          url,
          {
            method,
            headers: requestHeaders,
            body,
          },
          options.timeout || 30000,
        );
        const text = await response.text();
        return { response, text, json: parseJsonMaybe(text) };
      };

      let result = await sendOnce();
      if (canRelogin && looksLikeAuthError(result.response.status, result.json)) {
        try {
          headers.Cookie = await authService!.getCookieHeaderWithLogin({ forceLogin: true });
        } catch (error) {
          throw new Error(error instanceof Error ? error.message : String(error));
        }
        result = await sendOnce();
      }

      if (!result.response.ok) {
        throw new HttpStatusError(
          endpoint,
          result.response.status,
          result.response.statusText,
          result.text,
        );
      }
      if (!result.json) {
        throw new Error(`invalid JSON response from ${endpoint}`);
      }
      return result.json;
    };

    if (useBindings) {
      const rootDir = path.dirname(docsSyncHome!);
      const configForBindings = docsSyncConfig!;

      const dirToBindings = new Map<string, string[]>();
      for (const name of bindingNames) {
        const binding = configForBindings.bindings[name];
        if (!binding) {
          throw new Error(`binding not found: ${name}`);
        }
        const dirPath = resolveBindingDirForContext(
          docsSyncHome!,
          rootDir,
          process.cwd(),
          binding.dir,
        );
        const existing = dirToBindings.get(dirPath) || [];
        existing.push(name);
        dirToBindings.set(dirPath, existing);
      }
      const duplicates = Array.from(dirToBindings.entries()).filter(
        ([, names]) => names.length > 1,
      );
      if (duplicates.length) {
        const lines: string[] = [];
        lines.push("invalid docs-sync bindings: multiple bindings share the same dir");
        duplicates.forEach(([dirPath, names]) => {
          lines.push(`- dir=${dirPath} bindings=${names.join(", ")}`);
        });
        lines.push("");
        lines.push("Fix: split docs into separate directories (recommended).");
        lines.push("Example:");
        lines.push(
          "  yapi docs-sync bind update --name <bindingA> --dir docs/yapi-sync/<bindingA>",
        );
        lines.push(
          "  yapi docs-sync bind update --name <bindingB> --dir docs/yapi-sync/<bindingB>",
        );
        throw new Error(lines.join("\n"));
      }

      const bindingResults: Record<
        string,
        { binding: DocsSyncBinding; files: Record<string, DocsSyncFileInfo> }
      > = {};
      for (const name of bindingNames) {
        const binding = configForBindings.bindings[name];
        if (!binding) {
          throw new Error(`binding not found: ${name}`);
        }
        const dirPath = resolveBindingDirForContext(
          docsSyncHome!,
          rootDir,
          process.cwd(),
          binding.dir,
        );
        if (!fs.existsSync(dirPath) || !fs.statSync(dirPath).isDirectory()) {
          const scanRoot = findGitRoot(process.cwd()) || process.cwd();
          throw new Error(buildMissingBindingDirMessage(name, binding.dir, binding, scanRoot));
        }

        const runtimeBinding = cloneMappingForSync(binding, options.sourceFiles);
        const result = await syncDocsDir(dirPath, runtimeBinding, options, request);
        if (options.dryRun) {
          console.log(`dry-run preview binding=${name}`);
          result.previews.forEach((item) => console.log(buildDocsSyncPreviewLine(item)));
        }
        console.log(
          `synced=${result.updated} created=${result.created} skipped=${result.skipped} preview_only=${result.previewOnly} binding=${name} dir=${dirPath}`,
        );
        mergeSyncState(binding, runtimeBinding);
        bindingResults[name] = { binding, files: result.files };
      }

      if (!options.dryRun) {
        saveDocsSyncConfig(docsSyncHome!, configForBindings);
        await updateDocsSyncCaches(docsSyncHome!, baseUrl, bindingResults, request);
      }
    } else {
      for (const dir of dirs) {
        const dirPath = path.resolve(dir);
        if (!fs.existsSync(dirPath) || !fs.statSync(dirPath).isDirectory()) {
          throw new Error(`dir not found: ${dirPath}`);
        }

        const { mapping, mappingPath } = loadMapping(dirPath);
        const runtimeMapping = cloneMappingForSync(mapping, options.sourceFiles);
        const result = await syncDocsDir(dirPath, runtimeMapping, options, request);
        if (options.dryRun) {
          console.log(`dry-run preview dir=${dirPath}`);
          result.previews.forEach((item) => console.log(buildDocsSyncPreviewLine(item)));
        }

        if (!options.dryRun) {
          mergeSyncState(mapping, runtimeMapping);
          saveMapping(mapping, mappingPath);
        }

        console.log(
          `synced=${result.updated} created=${result.created} skipped=${result.skipped} preview_only=${result.previewOnly} dir=${dirPath}`,
        );
      }
    }

    return 0;
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 2;
  }
}
